### ISSUE TITLE
Can it support covariance type like "full" in sklearn?

### ISSUE THREAD

**Issue by cientgu** [ldeecke/gmm-torch#10]
I think the covariance matrix type is "diag" in sklearn, can it support "full" in sklearn?

**Comment by wjun0830** [comment]
I am also curious about this issue

**Comment by cientgu** [comment]
> I am also curious about this issue

I build the model in sklearn and convert to pytorch model and then forward.  Maybe you can refer to https://github.com/cientgu/GIQA/blob/e9cf85e82af8a7b8c8c0c858ab3650e1d829fa13/get_gmm.py#L30

**Comment by wjun0830** [comment]
> > I am also curious about this issue
> 
> I build the model in sklearn and convert to pytorch model and then forward. Maybe you can refer to https://github.com/cientgu/GIQA/blob/e9cf85e82af8a7b8c8c0c858ab3650e1d829fa13/get_gmm.py#L30

You mean you fit the GMM first on cpu, then use data on gpu?
Can't GMM with the full covariance matrix be run on gpu directly?

**Comment by cientgu** [comment]
> > > I am also curious about this issue
> > 
> > 
> > I build the model in sklearn and convert to pytorch model and then forward. Maybe you can refer to https://github.com/cientgu/GIQA/blob/e9cf85e82af8a7b8c8c0c858ab3650e1d829fa13/get_gmm.py#L30
> 
> You mean you fit the GMM first on cpu, then use data on gpu?
> Can't GMM with the full covariance matrix be run on gpu directly?

Yes.
Currently, I haven't implement it, if you found this implementation, please tell me, thanks.

**Comment by luyvlei** [comment]
> Has anyone had any luck adding full covariance support?

I add the support for full convairance, but it hasn't been thoroughly tested yet, so you can try it first. 
https://github.com/luyvlei/gmm_torch_fullcovariance

**Comment by ldeecke** [comment]
Thanks to @luyvlei this has been added. 👍
