### ISSUE TITLE
could you support Bayesian Information Criterion 

### ISSUE THREAD

**Issue by jornbowrl** [ldeecke/gmm-torch#11]
Thanks for your marvel Pytorch-Implemention.

could you support the Bayesian information criterion like "sklearn.mixture.GaussianMixture.bic", which measure the best model in unsupervised learn.

ps: BIC will just return a float value

**Comment by ldeecke** [comment]
Hi,

I've added this in 5e9f3073f90d0ba24672b13c5073205ddb38ac97. The function returns a `torch.float` tensor.

**Comment by jornbowrl** [comment]
good job ,thanks. I will test it completely .
