### ISSUE TITLE
The mu and var of each componet equal 0?

### ISSUE THREAD

**Issue by Michael-J98** [ldeecke/gmm-torch#13]
I made the model with 16 components to fit the output of an encoder which has 40 dims. 
And I found out the model.mu and model.var all equal to zero.
What should I do to fix it?

**Comment by ldeecke** [comment]
In principle, providing an adequate `n_components, d` should suffice.

Otherwise, please share the relevant parts of your code that reproduce this issue.

**Comment by Michael-J98** [comment]
Actually, using the test.py code in your repository is  OK. Change `d` to 10 or bigger, you'll find out mu&var go to zero by iterations.

**Comment by ldeecke** [comment]
I see. Thanks for pointing this out @Michael-J98.

The EM algorithm has been moved into log-space in f5a737b, which should resolve this issue.

**Comment by Michael-J98** [comment]
You're welcome. 
Really appreciate your effort!
