### ISSUE TITLE
Is there online update version?

### ISSUE THREAD

**Issue by ZJP-c4cld** [ldeecke/gmm-torch#14]
I  want to use GMM to estimate the distribution of data points. The idea I want to realize is ——  I use the first batch of data points to get 1st GMM. And I use 2nd batch of data points to update parameters in GMM and get 2nd version.  
        Is there online update version of GMM like I describe above?

**Comment by ldeecke** [comment]
For online versions of the algorithm, I would suggest looking into literature on incremental EM.

The implementation in this repository is close to that in sklearn, and there are currently no plans (at least on my part) to change this.
