### ISSUE TITLE
To determine the termination condition of EM algorithm iteration, the mean value of log_pdf should be taken instead of sum.

### ISSUE THREAD

**Issue by luyvlei** [ldeecke/gmm-torch#16]
The fit function will always Iterative 100 times if the sample size are big.

**Comment by ldeecke** [comment]
Good point, sklearn does this as well ([source](github.com/scikit-learn/scikit-learn/blob/2beed55847ee70d363bdbfe14ee4401438fba057/sklearn/mixture/_base.py#L282)). Added this in 97ac8cb.
