### ISSUE TITLE
How the log-likelihood calculation works in this code

### ISSUE THREAD

**Issue by vickycs50** [ldeecke/gmm-torch#17]
Dear 
         I have gone through this piece of code, however, can you please explain how loglikelihood is calculated in this example, I have seen few examples such as  [https://colab.research.google.com/drive/1Eb-G95_dd3XJ-0hm2qDqdtqMugLkSYE8#scrollTo=LF5plZfI5qiY](url), which use a multi-variate gaussian distribution to estimate the likelihood which is different from your code.

**Comment by ldeecke** [comment]
The calculation follows that of sklearn, c.f. their documentation: https://scikit-learn.org/stable/modules/generated/sklearn.mixture.GaussianMixture.html
