### ISSUE TITLE
gmm Sample error

### ISSUE THREAD

**Issue by Danden1** [ldeecke/gmm-torch#22]
![image](https://user-images.githubusercontent.com/13817715/153132285-1a165662-98ea-4606-a90a-2b090446231d.png)

When I use gmm.sample(...), this error is occurred.

In sample function,

    d_k = torch.distributions.multivariate_normal.MultivariateNormal(self.mu[0, k].double(), self.var[0, k].double())

add .doulbe(), this error is fixed.

**Comment by ldeecke** [comment]
Thanks for catching this. I wasn't able to reproduce the error, but 8e72b1d should address it.

Should this issue persist, please feel free to reopen.
