### ISSUE TITLE
What happens if i fit a model multiple times

### ISSUE THREAD

**Issue by Vichoko** [ldeecke/gmm-torch#4]
Does it continue training or it starts over?

I'm implementing batch training and this issue is crucial and not clear enough because docs say that implements `sklearn ` interface, but for `sklearn` [fit forgets everything](https://stackoverflow.com/questions/29095769/sklearn-gmm-on-large-datasets) if called multiple times.

Also, I couldn't find `partial_fit `or other workarounds.

I'm trying to fit a GMM with an amount of data that doesn't fit in memory.  
Is it even theoretically possible to train a GMM in batches? 

I can't even take a representative sample of the dataset because I'm working with multimedia data where a sample enough to fill the memory is less that 1% of the whole dataset.

**Comment by ldeecke** [comment]
Thanks for pointing this out. bdcc55a aligns `fit` with sklearn, so parameters will reset when calling this (or default to  `mu_init` or `var_init`).

**Comment by Vichoko** [comment]
@ldeecke 
So any workarounds for batch training? I can't figure this out yet
