### ISSUE TITLE
Score method (as sklearn's)

### ISSUE THREAD

**Issue by Vichoko** [ldeecke/gmm-torch#5]
First of all, I'm noting this method because readme says that this model follows sklearn's interface so I hoped to use these methods.

I'm talking about this [`gmm.score(X)`](https://scikit-learn.org/0.15/modules/generated/sklearn.mixture.GMM.html#sklearn.mixture.GMM.sample) method that [sklearn.mixture.GMM ](https://scikit-learn.org/0.15/modules/generated/sklearn.mixture.GMM.html) includes.

I couldn't find any method that does this.
Any suggestions to get this working?

**Comment by ldeecke** [comment]
I've added this, see a9beccd7cce8984c451515edb3e92a4e20fc8ffc.

**Comment by Vichoko** [comment]
Thank you so much!
