### ISSUE TITLE
Batch dimension support

### ISSUE THREAD

**Issue by nfsrules** [ldeecke/gmm-torch#6]
Hi Lucas, 

Thanks for your contribution!  After seeing the input data shape, I've noted that there's no batch dimension. Are you planning to add this support any time soon?

Best

**Comment by Vichoko** [comment]
The expected input size is (n, d), so `n` is the number of data points and `d` is the dimension of the feature vector. It could be `n` the dimension you are looking for?

What exactly do you mean with batch dimension?

**Comment by ldeecke** [comment]
I am reluctant to add this for two reasons:

* it would diverge significantly from the sklearn interface (which does not support batches),
* batch-wise optimization of GMMs is non-standard, so there is significant ambiguity to how the batch dimension would be handled internally, how the resulting model parameters are stored/returned etc.
