### ISSUE TITLE
Score method: 'GaussianMixture' object has no attribute 'pi'

### ISSUE THREAD

**Issue by Vichoko** [ldeecke/gmm-torch#8]
Hello, first of all, thank you for this amazing library and implementing the `score` method.

I just discovered this uncaught exception when calling `score` method on a non-fitted GMM instance.

I think instead of raising this AttributeError exception, this method should return a pseudo-random score, as the parameters could be random at the beginning. Or an ad-hoc exception for better handling.

## Stacktrace
```

  File "C:\Users\Vichoko\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\Vichoko\Git\aidio\torch_models.py", line 728, in forward
    x = self.forward_score(x)  # shape is (sample, frame, gmm)
  File "C:\Users\Vichoko\Git\aidio\torch_models.py", line 703, in forward_score
    log_prob = gmm.score(x)  # output shape is (samples*frames, )
  File "C:\Users\Vichoko\Git\aidio\util\gmm_torch\gmm.py", line 131, in score
    score = self.__score(self.pi, self.__p_k(x, self.mu, self.var), sum_data=False)
  File "C:\Users\Vichoko\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 591, in __getattr__
    type(self).__name__, name))
AttributeError: 'GaussianMixture' object has no attribute 'pi'
```

**Comment by Vichoko** [comment]
Just wanted to note that even after fit, the score method return an array of NaN, when sklearn's return only a float number under the same circunstamces (just fit and score a set of data points)

**Comment by ldeecke** [comment]
Thank you for pointing these out! C.f. 9b4d962.

* Renamed `score` to `score_samples` in accordance with how sklearn interface.
* Calling `score_samples` on a newly instantiated (i.e. non-fitted) GMM will no longer raise an exception.

**Comment by Vichoko** [comment]
Thank you! 

Just wanted to note that Sklearn's behavior of scoring a non-fitted GMM is to raise a NonFittedException.

**Comment by Vichoko** [comment]
> Calling score_samples on a newly instantiated (i.e. non-fitted) GMM will no longer raise an exception.

What's the behavior in this case, instead of raising an exception?
